name: SonarQube Analysis
on: [push, pull_request]

jobs:
  sonarqube:
    # Use self-hosted runner to access local SonarQube
    runs-on: self-hosted
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for full Git history

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: http://localhost:80
      with:
        # Project key must match your SonarQube project
        args: >
          -Dsonar.projectName="myproject"
