name: SonarQube Code Analysis

on: [push]

jobs:
  sonarqube:
    runs-on: self-hosted  # required to reach local SonarQube

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
