name: SonarQube Code Analysis

on: [push]

jobs:
  sonarqube:
    runs-on: self-hosted  # required to reach local SonarQube

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=myproject \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://127.0.0.1:80 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
